CLUSTAL multiple sequence alignment by MUSCLE (3.8)


African_Clawed_Frog       ----MERKV-LGLLIALGFLGSCLAEKNCRVDNFEVMKDFNKERYAGVWYAVAKKDPEGL
Domestic_Chicken          ----MAYTWRALLLLALAFLGSSMAERDCRVSSFKVKENFDKNRYSGTWYAMAKKDPEGL
Orca|                     ----MEWVW-ALVLLAA--LGSVRAERDCRVSSFRVKENFDKDRFSGTWYAMAKKDPKGL
Domestic_Pig              ----MEWVW-ALVLLAA--LGSAQAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGL
Human                     ----MKWVW-ALLLLAA--LGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGL
Common_Marmoset           ----MKWVW-ALLLLAV--LGISRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGL
Rainbow_Trout             --------------------------SDCQVSNIQVMQNFDRSRYTGRWYAVAKKDPVGL
Zebrafish                 ----------MLRLCIAVCVLATCWAQDCQVSNFAVQQDFNRTRYQGTWYAVAKKDPVGL
Drosophila_mayaguana      ---------------------------------ITSVGNLNMKKYQGIWYPQLSYPLYLH
mojavensis(fruitfly)      MLNQVFYISVILMLSLGSHALSTRISRGPCQANLTAVGDLNMRRYEGIWYPQFAYPLYHK
                                                           :    :::  .: * **.         

African_Clawed_Frog       FLLDNIAANFKIEDNGKTT------ATAKGRVRILDKLELCANMVGTFIETNDPAKYRMK
Domestic_Chicken          FLQDNVVAQFTVDENGQMS------ATAKGRVRLFNNWDVCADMIGSFTDTEDPAKFKMK
Orca|                     FLQDNIVAQF-MNENGHMT------ATAKGRVRLFNSWDLCADMLGTFTDTEDPAKFKMK
Domestic_Pig              FLQDNIVAEFSVDENGHMS------ATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMK
Human                     FLQDNIVAEFSVDETGQMS------ATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMK
Common_Marmoset           FLQDNIIAEFSVDETGQMS------ATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMK
Rainbow_Trout             FLLDNVVAQFSVDESGKVT------ATAHGRVIILNNWEMCANMFGTFEDTPDPAKFKMR
Zebrafish                 FLLDNIVANFKVEEDGTMT------ATAIGRVIILNNWEMCANMFGTFEDTEDPAKFKMK
Drosophila_mayaguana      PLPECAKFNIVKGKNGNYEIHRSDLDGKSGLLRQRTSLITKVDKKG--------GKYALK
mojavensis(fruitfly)      SLPKCVKYNVTKDISGKYRILRSDIDSQSGNVRRRSTLILRVSRKG--------GKYAIR
                           * .    :.     *             * :    .    ..  *        .*: :.

African_Clawed_Frog       YHGALAILERGLDDHWVVDTDYTTYAITYACRRRNLDGTCRDSYSFVFSRDINGLPSESQ
Domestic_Chicken          YWGVASFLQKGNDDHWVVDTDYDTYALHYSCRELNEDGTCADSYSFVFSRDPKGLPPEAQ
Orca|                     YWGVASFLQKGNDDHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFARDLNGFSPEVQ
Domestic_Pig              YWGVASFLQKGNDDHWIIDTDYDTYAVQYSCRLQNLDGTCADSYSFVFARDPHGFSPEVQ
Human                     YWGVASFLQKGNDDHWIVDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQ
Common_Marmoset           YWGVASFLQKGNDDHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQ
Rainbow_Trout             YWGAASYLQTGNDDHWVIDTDYDNYAIHYSCREVDLDGTCLDGYSFIFSRHPTGLRPEDQ
Zebrafish                 YWGAAAYLQTGYDDHWIIDTDYDNYAIHYSCRELDEDGTCLDGYSFIFSRHPDGLRPEDQ
Drosophila_mayaguana      MKNSHDGL-----DIYVLDTDYKTFSIQYAC--IEVDGNLNLAYAIILTRDRM---PDSK
mojavensis(fruitfly)      TDNSPDGL-----NMYVLDTDYRTYSIQYAC--IELEGILNIAYAVIMTRERM---PSSE
                            .    *     : :::**** .::: *:*   : :*    .*:.:::*      .. :

African_Clawed_Frog       RIVRRRQ-EQLCLDRKYRVV-VHNGYCETN------
Domestic_Chicken          KIVRQRQ-IDLCLDRKYRVI-VHNGFCS--------
Orca|                     RIVRQRQ-EELCLARQYRLI-AHNGYCDGESE----
Domestic_Pig              KIVRQRQ-EELCLARQYRII-THNGYCDGKSERNIL
Human                     KIVRQRQ-EELCLARQYRLI-VHNGYCDGRSERNLL
Common_Marmoset           RIIRQRQ-EELCLARQYRLI-VHNGYCDGKSERNLL
Rainbow_Trout             KIVTDKK-KEICFLGKYRRV-GHTGFCESS------
Zebrafish                 AIVTQKK-QDICFLGKYRRV-AHTGFCEAA------
Drosophila_mayaguana      VIKKSRKLAELSGVELRRLIPISQKSCPKDA-----
mojavensis(fruitfly)      VIQKTKQLAELSGIDQKKMVPILQGACPIDV-----
                           *   .:  ::.     . :      *         
