CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Drosophila_mayaguana      -----------------------------ITSVGNLNMKKYQGIWYPQLSY-PLYLHPLP
African_Clawed_Frog       MERKV-LGLLIALGFLGSCLAEKNCRVDNFEVMKDFNKERYAGVWYAVAKKDPEGLFLLD
Domestic_Chicken          MAYTWRALLLLALAFLGSSMAERDCRVSSFKVKENFDKNRYSGTWYAMAKKDPEGLFLQD
Orca                      MEWVW-ALVLLAA--LGSVRAERDCRVSSFRVKENFDKDRFSGTWYAMAKKDPKGLFLQD
Domestic_Pig              MEWVW-ALVLLAA--LGSAQAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQD
Human_PRGP                MKWVW-ALLLLAA--LGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQD
Common_Marmoset           MKWVW-ALLLLAV--LGISRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQD
Rainbow_Trout             ----------------------SDCQVSNIQVMQNFDRSRYTGRWYAVAKKDPVGLFLLD
Zebrafish                 ----M-LRLCIAVCVLATCWA-QDCQVSNFAVQQDFNRTRYQGTWYAVAKKDPVGLFLLD
                                                       :    :::  .: * **.  .  *  *.   

Drosophila_mayaguana      E-CAKFNIVK-GKNGNYEIHRSDLDGKSGLLRQRTSLITKVDKKGGKYALK-------MK
African_Clawed_Frog       NIAANFKIEDNGKTTATAKGRVRILDKLELCANMVGTFIETNDP-AKYRMKYHGALAILE
Domestic_Chicken          NVVAQFTVDENGQMSATAKGRVRLFNNWDVCADMIGSFTDTEDP-AKFKMKYWGVASFLQ
Orca                      NIVAQF-MNENGHMTATAKGRVRLFNSWDLCADMLGTFTDTEDP-AKFKMKYWGVASFLQ
Domestic_Pig              NIVAEFSVDENGHMSATAKGRVRLLNNWDVCADMVGTFTDTEDP-AKFKMKYWGVASFLQ
Human_PRGP                NIVAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDP-AKFKMKYWGVASFLQ
Common_Marmoset           NIIAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDP-AKFKMKYWGVASFLQ
Rainbow_Trout             NVVAQFSVDESGKVTATAHGRVIILNNWEMCANMFGTFEDTPDP-AKFKMRYWGAASYLQ
Zebrafish                 NIVANFKVEEDGTMTATAIGRVIILNNWEMCANMFGTFEDTEDP-AKFKMKYWGAAAYLQ
                          :  *:* : . *        *  : ..  :  :  . : .. .  .*: :.       ::

Drosophila_mayaguana      NSHDGLDIYVLDTDYKTFSIQYAC--IEVDGNLNLAYAIILTRDRM---PDSKVIKKSRK
African_Clawed_Frog       RGLD--DHWVVDTDYTTYAITYACRRRNLDGTCRDSYSFVFSRDINGLPSESQRIVRRRQ
Domestic_Chicken          KGND--DHWVVDTDYDTYALHYSCRELNEDGTCADSYSFVFSRDPKGLPPEAQKIVRQRQ
Orca                      KGND--DHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFARDLNGFSPEVQRIVRQRQ
Domestic_Pig              KGND--DHWIIDTDYDTYAVQYSCRLQNLDGTCADSYSFVFARDPHGFSPEVQKIVRQRQ
Human_PRGP                KGND--DHWIVDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQKIVRQRQ
Common_Marmoset           KGND--DHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQRIIRQRQ
Rainbow_Trout             TGND--DHWVIDTDYDNYAIHYSCREVDLDGTCLDGYSFIFSRHPTGLRPEDQKIVTDKK
Zebrafish                 TGYD--DHWIIDTDYDNYAIHYSCRELDEDGTCLDGYSFIFSRHPDGLRPEDQAIVTQKK
                           . *  * :::**** .::: *:*   : **.   .*:::::*      .: : *   .:

Drosophila_mayaguana      LAELSGVELRRLIPISQKSCPKDA-----
African_Clawed_Frog       -EQLCLDRKYRVV-VHNGYCETN------
Domestic_Chicken          -IDLCLDRKYRVI-VHNGFCS--------
Orca                      -EELCLARQYRLI-AHNGYCDGESE----
Domestic_Pig              -EELCLARQYRII-THNGYCDGKSERNIL
Human_PRGP                -EELCLARQYRLI-VHNGYCDGRSERNLL
Common_Marmoset           -EELCLARQYRLI-VHNGYCDGKSERNLL
Rainbow_Trout             -KEICFLGKYRRV-GHTGFCESS------
Zebrafish                 -QDICFLGKYRRV-AHTGFCEAA------
                            ::.     * :      *         
